smart_interaction.hint.press=Натисни
smart_interaction.hint.enter=щоб увійти
smart_interaction.hint.pick=щоби взяти
smart_interaction.hint.open=щоби відкрити
smart_interaction.hint.push=щоби натиснути